name: DummyCheck

on:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Replace secrets in Renovate configuration
        run: |
          ls -al
          sed -i "s#{{ secrets.OCI_REGISTRY_PASSWORD }}#${{ secrets.OCI_REGISTRY_PASSWORD }}#g" renovate.json

           cat renovate.json | grep '{{ secrets.OCI_REGISTRY_PASSWORD }}'
      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.6
        with:
          configurationFile: renovate.config.js
          token: ${{ secrets.GITHUB_TOKEN }}
          ociRegistryPassword: ${{ secrets.OCI_REGISTRY_PASSWORD }}
        env:
          OCI_REGISTRY_USERNAME: ${{ secrets.OCI_REGISTRY_USERNAME }}
          OCI_REGISTRY_PASSWORD: ${{ secrets.OCI_REGISTRY_PASSWORD }}
