name: DummyCheck

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' 

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run Renovate
        uses: renovatebot/github-action@24.114.2
        with:
          configurationFile: renovate.config.js
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          OCI_REGISTRY_USERNAME: ${{ secrets.OCI_REGISTRY_USERNAME }}
          OCI_REGISTRY_PASSWORD: ${{ secrets.OCI_REGISTRY_PASSWORD }}
